### ISSUE TITLE
Error  candle dbhlc ,pinnochio,dblhc,tbh

### ISSUE THREAD

**Issue by crypto-maniac** [n1nj4z33/iqpy#7]
Hello , i got these error when i activate the bot

i tried with different pattern but its same error
dbhlc ,pinnochio,dblhc , tbh,tbl 

exemple of error 

> Traceback (most recent call last):
>   File "starter.py", line 170, in <module>
>     start()
>   File "starter.py", line 146, in start
>     signal = signaler.get_signal()
>   File "/iqoptionbot/signaler.py", line 59, in get_signal
>     if pattern.put():
>   File "iqoptionbot/patterns/dbhlc.py", line 20, in put
>     if self.candles.first_candle.candle_high == self.candles.second_candle.candle_high:
> AttributeError: 'NoneType' object has no attribute 'first_candle'

or 

> Traceback (most recent call last):
>   File "starter.py", line 170, in <module>
>     start()
>   File "starter.py", line 146, in start
>     signal = signaler.get_signal()
>   File "/iqoptionbot/signaler.py", line 55, in get_signal
>     if pattern.call():
>   File "/iqoptionbot/patterns/tbh.py", line 20, in call
>     if self.candles.first_candle.candle_high == self.candles.second_candle.candle_high:
> AttributeError: 'NoneType' object has no attribute 'second_candle'

any help would be appreciated 

thanks you very much

**Comment by end1an** [comment]
I have same problem ++

**Comment by crypto-maniac** [comment]
use this one but its not a win bot 
[TurboTrading-Martingale original.py.zip](https://github.com/n1nj4z33/iqoptionbot/files/949037/TurboTrading-Martingale.original.py.zip)

**Comment by end1an** [comment]
I will try thank you @crypto-maniac

**Comment by end1an** [comment]
Why TurboTrading bot does not a win bot?
@crypto-maniac

**Comment by tolawho** [comment]
I have same problem :(. Anyone have solution for this. @n1nj4z33 please help

**Comment by lucianopinheiro** [comment]
That happens because the event to get a candle from web is asyncronous. So, when it is "changing" candles, you can have a test, and no candle at variable. The best solution is to have a solution so you get candles from asyncronous queue and transform it to a syncronous queue.
The workaround is to test the existence of that candle with `try`.

**Comment by AllenUchiha** [comment]
> use this one but its not a win bot
TurboTrading-Martingale original.py.zip

Kindly give credits when you're sending my codes to somewhere else
